installerInfo: '{ "productId": "OnPremObservability-Splunk/1.0.0", "features": [ { "featureId": "ArtifactoryVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}" }, { "featureId": "{{ if .Values.postgresql.enabled }}postgresql{{ else }}{{ .Values.database.type }}{{ end }}/0.0.0" }, { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}" },  { "featureId": "Channel/OnPremObservability-Splunk-Helm" } ] }'
artifactory:
  customInitContainersBegin: |
    - name: "prepare-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/;
          curl https://raw.githubusercontent.com/jfrog/log-analytics-splunk/master/fluent.conf.rt -o {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: volume
  customSidecarContainers: |
    - name: "artifactory-fluentd-sidecar"
      image: "releases-pts-observability-fluentd.jfrog.io/fluentd:4.0"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.artifactory.persistence.mountPath }}
        - name: JPD_URL
          value: {{ .Values.jfrog.observability.jpd_url }}
        - name: JPD_ADMIN_USERNAME
          value: {{ .Values.jfrog.observability.username }}
        - name: JFROG_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: jfrog-admin-token
              key: token
        - name: COMMON_JPD
          value: {{ .Values.jfrog.observability.common_jpd | quote }}
        - name: SPLUNK_COM_PROTOCOL
          value: {{ .Values.splunk.com_protocol }}
        - name: SPLUNK_HEC_HOST
          value: {{ .Values.splunk.host }}
        - name: SPLUNK_HEC_PORT
          value: {{ .Values.splunk.port | quote}}
        - name: SPLUNK_METRICS_HEC_TOKEN
          value: {{ .Values.splunk.metrics_token }}
        - name: SPLUNK_HEC_TOKEN
          value: {{ .Values.splunk.logs_token }}
        - name: SPLUNK_INSECURE_SSL
          value: {{ .Values.splunk.insecure_ssl | quote}}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
splunk:
  host: SPLUNK_HEC_HOST
  port: SPLUNK_HEC_PORT
  logs_token: SPLUNK_HEC_TOKEN
  metrics_token: SPLUNK_METRICS_HEC_TOKEN
  com_protocol: SPLUNK_COM_PROTOCOL
  insecure_ssl: SPLUNK_INSECURE_SSL
jfrog:
  observability:
    jpd_url: JPD_URL
    username: JPD_ADMIN_USERNAME
    common_jpd: COMMON_JPD